---
- include: centos.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 6

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Start and enable service
  service: name=nginx state=started enabled=yes

- name: Adding Kibana conf
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=0644
  notify: reload nginx