---
- name: Disabling SElinux 
  selinux: state=disabled

- include: yum.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - install

- include: apt.yml
  when: ansible_os_family == 'Debian'
  tags:
    - install

- name: Create the Kibana directories
  file: path={{ item }} owner=kibana group=kibana state=directory
  with_items:
    - "{{ kibana_logs_dir }}"
  tags:
    - install

- name: install /opt/kibana/conf/kibana.yml
  template: >-
    src=kibana.yml.j2
    dest=/opt/kibana/config/kibana.yml
    owner=root
    group=root
    mode=0644
  notify: restart kibana
  tags:
    - install
