---
- name: Disabling SElinux 
  selinux: state=disabled

- include: yum.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - install

- include: apt.yml
  when: ansible_os_family == 'Debian'
  tags:
    - install

- name: Create the Elasticsearch directories.
  file: path={{ item }} owner=elasticsearch group=elasticsearch state=directory
  with_items:
    - "{{ es_data_dir }}"
    - "{{ es_logs_dir }}"
    - "{{ es_plugins_dir }}"
  tags:
    - install

- name: install /etc/elasticsearch/elasticsearch.yml
  template: >-
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=root
    mode=0644
  notify: restart elasticsearch
  tags:
    - install