---
- include: yum.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - install

- include: apt.yml
  when: ansible_os_family == 'Debian'
  tags:
    - install

- name: Create the Elasticsearch directories.
  file: path={{ item }} owner=elasticsearch group=elasticsearch state=directory
  with_items:
    - "{{ es_data_dir }}"
    - "{{ es_logs_dir }}"
    - "{{ es_plugins_dir }}"
  tags:
    - install

- name: Initial Elasticsearch configuration.
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^#?\s*cluster\.name', line: "cluster.name: {{ es_cluster_name }}" }
    - { regexp: '^#?\s*node\.name', line: "node.name: {{ inventory_hostname }}" }
    - { regexp: '^#?\s*path\.data', line: "path.data: {{ es_data_dir }}" }
    - { regexp: '^#?\s*path\.logs', line: "path.logs: {{ es_logs_dir }}" }
    - { regexp: '^#?\s*path\.plugins', line: "path.plugins: {{ es_plugins_dir }}" }
    - { regexp: '^#?\s*network\.bind_host', line: 'network.bind_host: "{{ es_bind_host }}"' }
    - { regexp: '^#?\s*network\.publish_host', line: 'network.publish_host: "{{ es_publish_host }}"' }
    - { regexp: '^#?\s*discovery\.zen\.ping\.unicast\.hosts:', line: "discovery.zen.ping.unicast.hosts: [{{ elasticsearch_cluster_hosts }}]" }
    - { regexp: '^#?\s*node\.master', line: 'node.master: "{{ elasticsearch_master }}"' }
    - { regexp: '^#?\s*node\.max_local_storage_nodes', line: 'node.max_local_storage_nodes: "{{ node_max_local_storage_nodes }}"' }
    - { regexp: '^#?\s*node\.data', line: 'node.data: "{{ node_data }}"' }
  notify: restart elasticsearch
  tags:
    - install
