- name: Add Elasticsearch gpg key
  rpm_key: key=https://packages.elastic.co/GPG-KEY-elasticsearch state=present
  tags:
    - install

- name: Add Elasticsearch repository.
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644

- name: Install Elasticsearch
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - curl
    - java-1.7.0-openjdk
    - elasticsearch
  tags:
    - install
# optional part of installation to configure firewall
- name: start firewalld
  service: name=firewalld state=started

- name: Adding Logstash and Kibana firewall rule
  firewalld: port=9200/tcp zone=public permanent=true state=enabled 

- name: Adding Elasticsearch cluster firewall rule
  firewalld: port=9300/tcp zone=public permanent=true state=enabled

- name: reload firewalld
  service: name=firewalld state=reloaded